# Generated by Django 2.1.5 on 2019-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_squashed_0005_remove_product_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
